### ISSUE TITLE
Panic when running example (in i3-wm)

### ISSUE THREAD

**Issue by azerupi** [PistonDevelopers/piston_window#121]
I get the following panic when trying to run the example:

```
thread '<main>' panicked at 'Failed to get root window: XError { description: "GLXBadFBConfig", error_code: 181, request_code: 155, minor_code: 34 }', ../src/libcore/result.rs:709
Process didn't exit successfully: `target/debug/piston_test` (exit code: 101)
```

I have no idea what is causing it but I am running Arch Linux with I3-wm, maybe that is causing some trouble somehow? I don't know. Let me know if I can procure more useful information.

**Comment by gregkatz** [comment]
I'm getting this on the hello world example too.

I'm on Debian GNU/Linux 8.4 (jessie) on an i686
rustc --version:
rustc 1.8.0 (db2939409 2016-04-11)

**Comment by Bluebird45** [comment]
````
Failed to get root window
````

You will need to add these lines and change the version to 2_1:

````
fn main() {

    // Change this to OpenGL::V2_1 if not working.
    let opengl = OpenGL::V2_1;                // this line
    
    let title = "Hello Piston! (press any key to enter inner loop)";
    let mut window: PistonWindow = WindowSettings::new(title, [640, 480])
    	.opengl(opengl)                    // and this line
        .exit_on_esc(true)
        .build()
        .unwrap_or_else(|e| { panic!("Failed to build PistonWindow: {}", e) });
````

**Comment by gregkatz** [comment]
Thank you for the response. Unfortunately that change gives me a different error:
thread '<main>' panicked at 'Error after executing command BindProgram(0): InvalidEnum', /home/xxx/.cargo/registry/src/github.com-48ad6e4054423464/gfx_device_gl-0.9.0/src/lib.rs:283

Seems like someone else had the same issue but it magically disappeared for that person:

http://stackoverflow.com/questions/36810775/invalidenum-error-in-piston

**Comment by Bluebird45** [comment]
Yes, that was me, and I think what you need to do now is to "cargo update" to overcome the new error.

**Comment by gregkatz** [comment]
Hmm, I did a cargo clean and cargo update, but no change on that error. Unfortunately I can't put any more time into it.

**Comment by AdrianArroyoCalle** [comment]
Hi, I've experienced the same error on Windows (BindProgram(0): InvalidEnum). However, I changed the piston_window version from 0.61 to 0.59 and now it works. Something done not so long ago has made this error.
