### ISSUE TITLE
Occasional panic upon closing window

### ISSUE THREAD

**Issue by Kasran** [PistonDevelopers/piston_window#149]
I have this very simple application that compiles and runs:

```rust
extern crate piston_window;

use piston_window::*;
use std::f64::consts::PI;

fn main() {
    let mut window: PistonWindow = WindowSettings::new(
        "piston-tutorial",
        [600, 600]
    )
    .exit_on_esc(true)
    .build()
    .expect("Could not make window");

    let mut i: f64 = 0.0;

    while let Some(e) = window.next() {
        window.draw_2d(&e, |c, g| {
            clear([0.5, 0.5, 0.5, 1.0], g);
            let center = c.transform.trans(300.0, 300.0);
            let square = rectangle::square(0.0, 0.0, 100.0);
            let red = [1.0, 0.0, 0.0, 1.0];
            // We translate the rectangle slightly so that it's centered; otherwise only the top left corner would be centered

            rectangle(red, square, center.rot_rad(i*PI/180.0).trans(-50.0, -50.0), g);
            i += 1.0;
        });
    }
}
```

It's a slight modification of some example I found - it merely displays a rotating red square on a gray background. The only dependency in Cargo.toml is `piston_window = "*"`.

It compiles, runs, and behaves as expected, except that sometimes when I close the window with the X button in the corner (seemingly never by pressing Esc) I get this panic message (with `RUST_BACKTRACE=1`):

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: 6, message: "The handle is invalid." } })', ../src/libcore\result.rs:746
stack backtrace:
   0:           0x9f3e53 - <unknown>
   1:           0x9f3345 - <unknown>
   2:           0x9b723f - <unknown>
   3:           0x9b8dcb - <unknown>
   4:           0x9e653b - <unknown>
   5:           0xa08495 - <unknown>
   6:           0x5feb07 - <unknown>
   7:           0x5fe955 - <unknown>
   8:           0x5fe8be - <unknown>
   9:           0x438674 - <unknown>
  10:           0x40166a - <unknown>
  11:           0x9f297d - <unknown>
  12:           0x9f27aa - <unknown>
  13:           0x460cba - <unknown>
  14:           0x4013b4 - <unknown>
  15:           0x4014e7 - <unknown>
  16:     0x7ffa82cb8101 - <unknown>
error: Process didn't exit successfully: `target\debug\piston-tutorial.exe` (exit code: 101)
```

What is this error coming from, and is there any way to prevent it?

I'm running Windows 10 x64, with a freshly-installed Rust 1.9.0 GNU. Any help would be appreciated.

**Comment by nilamo** [comment]
I noticed that I get the same (IOError) when exiting using the "x", right clicking and closing from the taskbar, as well as killing from task manager.  The error does NOT appear when using escape, with exit_on_esc enabled.  The specific IOError is not always the same.  For example, sometimes it's 'repr: Os { code: 2004, message: "The requested transformation operation is not supported." }',  while other times the error is 'repr: Os { code: -1073283066, message: "OS Error -1073283066 (FormatMessageW() returned error 317)" }'

**Comment by Xaeroxe** [comment]
Glutin has a function called `make_current` for its window that can fail, however the OpenGLWindow interface assumes this function will always succeed.  I feel this should be modified to return `Result` instead of `()` so that the error can be trapped and handled properly by the calling code.  I'm experiencing this issue, here is my backtrace:

```
thread 'tests::display_window' panicked at 'called `Result::unwrap()` on
 an `Err` value: IoError(Error { repr: Os { code: -1073283066, message: "OS Erro
r -1073283066 (FormatMessageW() returned error 317)" } })', src\libcore\result.r
s:859
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:365
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: core::result::unwrap_failed<glutin::ContextError>
             at C:\projects\rust\src\libcore\macros.rs:29
   9: core::result::Result<(), glutin::ContextError>::unwrap<(),glutin::ContextE
rror>
             at C:\projects\rust\src\libcore\result.rs:737
  10: glutin_window::{{impl}}::make_current
             at C:\Users\kiese\.cargo\registry\src\github.com-1ecc6299db9ec823\p
istoncore-glutin_window-0.37.0\src\lib.rs:430
  11: piston_window::PistonWindow<glutin_window::GlutinWindow>::draw_2d<glutin_w
indow::GlutinWindow,input::Input,closure,()>
             at C:\Users\kiese\.cargo\registry\src\github.com-1ecc6299db9ec823\p
iston_window-0.66.0\src\lib.rs:208
```
My code starts here
```
  12: nitro::run
             at .\src\lib.rs:11
  13: nitro::tests::display_window
             at .\src\lib.rs:24
  14: test::{{impl}}::call_box<(),closure>
           at C:\projects\rust\src\libtest\lib.rs:140
  15: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  16: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
             at C:\projects\rust\src\libstd\panicking.rs:450
  17: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  18: alloc::boxed::{{impl}}::call_box<(),closure>
             at C:\projects\rust\src\liballoc\boxed.rs:640
  19: std::sys::imp::thread::{{impl}}::new::thread_start
             at C:\projects\rust\src\libstd\sys\windows\thread.rs:50
  20: BaseThreadInitThunk
```
