### ISSUE TITLE
panic while creating window with version `0.68.0`

### ISSUE THREAD

**Issue by andrewhickman** [PistonDevelopers/piston_window#201]
The following works fine with version `0.67.0` but panics with ``called `Option::unwrap()` on a `None` value`` on `0.68.0`.

```
extern crate piston_window;

use piston_window::{PistonWindow, WindowSettings};

fn main() {
    let _ = WindowSettings::new("Hello Piston!", (640, 480)).build::<PistonWindow>();
}
```
Backtrace:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:335
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: core::panicking::panic
             at C:\projects\rust\src\libcore\panicking.rs:49
   9: core::option::Option<&winit::platform::platform::events_loop::ThreadLocalData>::unwrap<&winit::platform::platform::events_loop::ThreadLocalData>
             at C:\projects\rust\src\libcore\macros.rs:21
  10: winit::platform::platform::events_loop::send_event::{{closure}}
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.7.4\src\platform\windows\events_loop.rs:268
  11: std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<winit::platform::platform::events_loop::ThreadLocalData>>>::with<core::cell::RefCell<core::option::Optio
n<winit::platform::platform::events_loop::ThreadLocalData>>,closure,()>
             at C:\projects\rust\src\libstd\thread\local.rs:265
  12: winit::platform::platform::events_loop::send_event
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.7.4\src\platform\windows\events_loop.rs:266
  13: winit::platform::platform::events_loop::callback
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.7.4\src\platform\windows\events_loop.rs:305
  14: CallWindowProcW
  15: CallWindowProcW
  16: GetTopWindow
  17: KiUserCallbackDispatcher
  18: NtUserCreateWindowEx
  19: CreateWindowExW
  20: CreateWindowExW
  21: CreateWindowExW
  22: glutin::api::wgl::load_extra_functions
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.9.0\src\api\wgl\mod.rs:703
  23: glutin::api::wgl::Context::new
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.9.0\src\api\wgl\mod.rs:91
  24: glutin::platform::platform::context::Context::new
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.9.0\src\platform\windows\context.rs:71
  25: glutin::platform::platform::Context::new
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.9.0\src\platform\windows\mod.rs:69
  26: glutin::GlWindow::new
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.9.0\src\lib.rs:322
  27: glutin_window::GlutinWindow::new
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\pistoncore-glutin_window-0.38.0\src\lib.rs:102
  28: glutin_window::{{impl}}::build_from_window_settings
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\pistoncore-glutin_window-0.38.0\src\lib.rs:399
  29: window::WindowSettings::build<glutin_window::GlutinWindow>
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\pistoncore-window-0.27.0\src\lib.rs:387
  30: piston_window::{{impl}}::build_from_window_settings<glutin_window::GlutinWindow>
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\piston_window-0.68.0\src\lib.rs:145
  31: window::WindowSettings::build<piston_window::PistonWindow<glutin_window::GlutinWindow>>
             at C:\Users\andre\.cargo\registry\src\github.com-1ecc6299db9ec823\pistoncore-window-0.27.0\src\lib.rs:387
  32: game::main
             at .\src\main.rs:6
  33: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  34: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:52
  35: main
  36: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  37: BaseThreadInitThunk
```

OpenGL version is 4.5.0, graphics driver is NVIDIA 382.05.

**Comment by bvssvni** [comment]
Have you tried specifying a different `OpenGL` version?

```rust
extern crate piston_window;

use piston_window::{OpenGL, PistonWindow, WindowSettings};

fn main() {
    let _ = WindowSettings::new("Hello Piston!", (640, 480)).opengl(OpenGL::V3_1.build::<PistonWindow>();
}
```

**Comment by andrewhickman** [comment]
I can't seem to reproduce this anymore, closing.
